apiVersion: v1
kind: Service
metadata:
  name: flask-rds-service
  labels:
    app: flask-rds
spec:
  type: NodePort
  selector:
    app: flask-rds
  ports:
    - protocol: TCP
      port: 80             # The port your application listens on
      targetPort: 80       # The port inside the container
      nodePort: 30080      # The port on your host machine (must be between 30000-32767)

