project_name: hof
builds:
  - binary: hof
    main: main.go
    ldflags:
      - -s -w
      - -X github.com/opentofu/opentofu/internal/hof/cmd/hof/verinfo.Version={{.Version}}
      - -X github.com/opentofu/opentofu/internal/hof/cmd/hof/verinfo.Commit={{.FullCommit}}
      - -X github.com/opentofu/opentofu/internal/hof/cmd/hof/verinfo.BuildDate={{.Date}}
      - -X github.com/opentofu/opentofu/internal/hof/cmd/hof/verinfo.BuildOS={{.Os}}
      - -X github.com/opentofu/opentofu/internal/hof/cmd/hof/verinfo.BuildArch={{.Arch}}
      - -X github.com/opentofu/opentofu/internal/hof/cmd/hof/verinfo.BuildArm={{.Arm}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}'
archives:
  - format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - thisfiledoesnotexist*
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  disable: false
  draft: false
  github:
    owner: hofstadter-io
    name: hof
dockers:
  - skip_push: false
    dockerfile: ../../ci/hof/docker/Dockerfile.debian
    image_templates:
      - hofstadter/{{.ProjectName}}:{{.Tag}}
      - hofstadter/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}
      - hofstadter/{{.ProjectName}}:v{{ .Major }}
      - hofstadter/{{.ProjectName}}:latest
      - hofstadter/{{.ProjectName}}:{{.Tag}}-debian
      - hofstadter/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}-debian
      - hofstadter/{{.ProjectName}}:v{{ .Major }}-debian
      - hofstadter/{{.ProjectName}}:latest-debian
  - skip_push: false
    dockerfile: ../../ci/hof/docker/Dockerfile.alpine
    image_templates:
      - hofstadter/{{.ProjectName}}:{{.Tag}}-alpine
      - hofstadter/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}-alpine
      - hofstadter/{{.ProjectName}}:v{{ .Major }}-alpine
      - hofstadter/{{.ProjectName}}:latest-alpine
  - skip_push: false
    dockerfile: ../../ci/hof/docker/Dockerfile.scratch
    image_templates:
      - hofstadter/{{.ProjectName}}:{{.Tag}}-scratch
      - hofstadter/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}-scratch
      - hofstadter/{{.ProjectName}}:v{{ .Major }}-scratch
      - hofstadter/{{.ProjectName}}:latest-scratch
