apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-rds-deployment
  labels:
    app: flask-rds
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-rds
  template:
    metadata:
      labels:
        app: flask-rds
    spec:
      containers:
      - name: flask-rds
        image: registry.gitlab.com/flashresolve1/augur:v1
        ports:
        - containerPort: 80

