project_name: mantis

builds:
  - binary: mantis
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# archives:
#   - format: tar.gz
#     name_template: >-
#       {{ .ProjectName }}_
#       {{- title .Os }}_
#       {{- if eq .Arch "amd64" }}x86_64
#       {{- else if eq .Arch "386" }}i386
#       {{- else }}{{ .Arch }}{{ end }}
#       {{- if .Arm }}v{{ .Arm }}{{ end }}
#     format_overrides:
#     - goos: windows
#       format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# release:
#   github:
#     owner: your_github_username
#     name: your_repo_name


blobs:
  - provider: s3
    bucket: mantis-public-releases
    region: us-east-2

brews:
-
  name: mantis
  homepage: https://getaugur.ai
  commit_author:
      name: kaushil24
      email: kaushil.kundalia@getaugur.ai
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  repository:
      owner: Pranil

      name: homebrew-mantis

      # Optionally a branch can be provided.
      #
      # Default: default repository branch.
      # Templates: allowed.
      branch: main

      # Optionally a token can be provided, if it differs from the token
      # provided to GoReleaser
      #
      # Templates: allowed.
      token: "{{ .Env.GITHUB_PERSONAL_AUTH_TOKEN }}"